### PR TITLE
Ignore old 'searchFunction' responses coming too late

### PR DESCRIPTION
**Pull request by azmeuk**
As discussed in #42, while typing a keyword, several requests are generated. However we do not have any guarantee that the order the responses are received in the order the requests are sent. This may lead to responses to old requests coming after responses to recent requests, and produce a very confusing user experience.
For instance, while typing `linux` you generate requests for `l`, `li`, `lin`, `linu` and `linux`, but for some reasons (network randomness, server being slow on a particular query) you may receive matching data in this order: `l`, `li`, `linu`, `linux` and finally `lin`. In that case the component will propose autocompletion for `lin`.

This patch fixes this by:
- passing a new `requestId` parameter to `searchFunction`. This `requestId` parameter is inspired from [datatables serverside processing](https://datatables.net/manual/server-side) `draw` parameter. This is the number of the request (the first time `searchFunction` is called this is `0`, the second time this is `1` and so on)
- a new dataformat to be returned by the server. Instead of a list of items, the server can now return a dictionary containing two keys:
  - `data` that holds the list of items;
  - `responseId` that must be the very same value that has been passed to the request as `requestId`.

This way the component can keep track of which request has received a response last, and ignore responses to older requests.

The behavior is retrocompatible, so old code wont break.

### CODE REVIEW

**Comment by azmeuk** [comment]
I rebased against master to solve conflicts.

**Comment by pstanoev** [comment]
@azmeuk I like the intention in this PR, having the counter as parameter to the search function is maybe OK, but relying on the search function to return result with the counter back seems like a complication that can maybe avoided.
I was thinking if this can be solved more on the component level...
Will give it more thought.

Thanks for the contribution so far, the previous PRs are merged and available in new version of the component, 1.3.0.
I've adapted some stuff but the properties are like you named them.

Cheers!

**Comment by azmeuk** [comment]
> @azmeuk I like the intention in this PR, having the counter as parameter to the search function is maybe OK, but relying on the search function to return result with the counter back seems like a complication that can maybe avoided.

For the record, this is how [datatables server-side processing](https://datatables.net/manual/server-side) handles the case.

>  I was thinking if this can be solved more on the component level...

What do you mean?

> Thanks for the contribution so far, the previous PRs are merged and available in new version of the component, 1.3.0.

:tada: :tada: :tada: 

For the context, I use simple-svelte-autocomplete for a professional project. Data is loaded exclusively asynchronously because it is huge: I deal with French addresses, cities, and other administrative divisions, so there is no way I can load all this data client-side. Sometimes it can take a few seconds to generate the whole list of items.

I have performances constraints so:
- items must be loaded as fast as possible
- the first item must be rendered faster than the last item in the list
- the server needs not to be too much requested
- user experience must be kept satisfying, even on low-bandwidth situations

With all the PR I have submitted (plus more) the result is pretty good!

**Comment by azmeuk** [comment]
@pstanoev I gave this issue some thoughts and here is something better and simpler:

- searchFunction does not have to been passed a `requestId` parameter
- responses to old queries are automatically ignored, and this is the default behavior \o/

What do you think?

**Pull request merged**
